name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main # Deploy to gh-pages whenever changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
          enable_jekyll: false
          exclude_assets: |
            .github/
            flask_app/env
            **/.*                  
            README.md
