name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flask_app/requirements.txt  # Correct path to requirements

      # Remove or comment out the test step if it still exists
      # - name: Run tests
      #   run: |
      #     pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: root
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          script: |
            cd /path/to/your/app  # Change this to the correct path on your server
            docker-compose down
            docker-compose up -d --build
