name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -r flask_app/requirements.txt

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | heroku auth:token

      - name: Create Procfile for Gunicorn
        run: |
          echo "web: gunicorn flask_app.app:app" > Procfile

      - name: Deploy to Heroku
        run: |
          git init
          git add .
          git commit -m "Deploying to Heroku"
          heroku git:remote -a team6-project-cicd
          git push -f heroku main
