name: Deploy Dynamic Website to Digital Ocean

on:
  push:
    branches:
      - main
      - gh-pages
  pull_request:
    branches:
      - main
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flask_app/requirements.txt

      - name: Run tests
        run: |
          # Run any tests you have here
          pytest

      - name: Build the application
        run: |
          # Placeholder for build steps (optional)
          echo "Building the Flask app..."

      - name: Deploy to DigitalOcean
        env:
          DO_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no root@137.184.215.215 "\
            cd /root/cicd && \
            git pull origin ${{ github.ref_name }} && \
            source /root/cicd/venv/bin/activate && \
            pip install -r flask_app/requirements.txt && \
            systemctl restart your-app.service \
          "
