name: Deploy Dynamic Website to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flask_app/requirements.txt

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@137.184.215.215 "\
            cd /root/cicd && \
            git pull origin main && \
            python3 -m venv /root/cicd/venv && \
            source /root/cicd/venv/bin/activate && \
            pip install --upgrade pip && \
            pip install -r flask_app/requirements.txt && \
            systemctl restart your-app.service \
          "
